# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CSS-SAC
version:      0.06
version_from: SAC.pm
installdirs:  site
requires:
    Class::ArrayObjects:           0.04
    Text::Balanced:                1.84

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
